# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2U_sh76c7I4RjWqfl0UJe39Okd-tF_9
"""

!pip install tensorflow pillow

pip install tensorflow==2.12.1

from google.colab import files

uploaded = files.upload()

import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

model = load_model('keras_model.h5')

img_path = 'dog5.jpeg'
img = image.load_img(img_path, target_size=(224, 224))
plt.imshow(img)
plt.axis('off')
plt.show()

img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.0

predictions = model.predict(img_array)
predicted_class = np.argmax(predictions[0])

class_names = ['dog', 'cat']
print(f"Predicted class: {class_names[predicted_class]}")